import type { SiteContent } from './types';

export const ko: SiteContent = {
  htmlLang: 'ko',
  meta: {
    title: '오뉴월컴퍼니 | 화장품 OEM ODM 소량생산 전문',
    description:
      '오뉴월컴퍼니는 화장품 OEM·ODM 소량생산 전문 제조 파트너입니다. 제형 개발부터 콘셉트 기획·디자인·패키징·제조·출고·수출까지 하나의 흐름으로 연결합니다. 코스메슈티컬·더마코스메틱·반영구색소 제조.',
    keywords:
      '오뉴월컴퍼니, 오뉴월 컴퍼니, 오뉴월, 오뉴월의새벽, 오뉴월의 새벽, 화장품 OEM, 화장품 ODM, 화장품 소량생산, 화장품 소량제작, 소량 OEM, 화장품 제조업체, 코스메슈티컬, 더마코스메틱, 반영구색소, 스킨케어 OEM, 세럼 제작, 크림 제작, 화장품 브랜드 런칭',
    ogTitle: '오뉴월컴퍼니 | 화장품 OEM ODM 소량생산',
    ogDescription:
      '화장품 OEM·ODM 소량 생산. 제형 개발부터 디자인·패키징·제조·수출까지 하나의 흐름으로.',
  },
  nav: {
    about: 'About',
    services: 'Services',
    capabilities: 'Capabilities',
    moq: 'MOQ',
    pricing: 'Price',
    process: 'Process',
    partners: 'Partners',
    contact: 'Contact',
    cta: '문의하기',
    langLabel: 'EN',
  },
  hero: {
    eyebrow: 'onewwol company',
    title: '소량부터 시작하는,\n나만의 브랜드',
    body: '제형 개발부터 콘셉트 기획, 디자인·패키징, 제조·출고, 수출까지\n나누지 않고 하나의 흐름으로 잇습니다.',
    primaryCta: '상담 신청하기',
    secondaryCta: '단가표 보기',
  },
  about: {
    eyebrow: 'About',
    title: 'One-stop Brand Partner',
    body: '제품 개발부터 콘셉트 기획, 디자인·패키징, 제조·출고, 수출까지\n브랜드가 나누어 관리해야 했던 과정을 하나의 흐름으로 연결합니다.',
    features: [
      'Concept Planning',
      'Formula Development',
      'Package Design',
      'Manufacturing',
      'Export Support',
      'After Care',
    ],
  },
  services: {
    eyebrow: 'Services',
    title: 'ODM · OEM · Consulting',
    body: '브랜드의 단계와 목적에 맞춰 세 가지 협업 방식을 제공합니다.',
    cardCta: '문의로 이동',
    items: [
      {
        key: 'odm',
        label: 'ODM',
        description:
          '시장 트렌드와 브랜드 방향을 분석하여 콘셉트 제안부터 제품 개발, 생산까지 주도적으로 제공합니다.',
        tags: ['Concept', 'Formula', 'Design', 'Manufacturing'],
      },
      {
        key: 'oem',
        label: 'OEM',
        description:
          '브랜드가 제시한 사양과 의견을 기반으로 개발·생산 전 과정을 협업하여 제공합니다.',
        tags: ['Specification', 'Sampling', 'Production', 'Aftercare'],
      },
      {
        key: 'consulting',
        label: 'Consulting',
        description:
          '브랜드 초기 기획, 제품 구성, 패키지 방향, 생산 조건 검토까지 실질적인 실행 기준을 함께 정리합니다.',
        tags: ['Planning', 'MOQ', 'Package', 'Launch'],
      },
    ],
  },
  capabilities: {
    eyebrow: 'Capabilities',
    title: 'Production Capabilities',
    body: '다양한 화장품 카테고리의 개발과 생산을 지원합니다.',
    groups: [
      {
        key: 'skincare',
        title: '스킨케어',
        items: ['스킨 / 토너', '에센스 / 세럼 / 앰플', '크림 / 로션', '미스트 / 오일'],
      },
      {
        key: 'cleanser',
        title: '클렌저 / 필링',
        items: [
          '클렌징 폼 / 젤',
          '오일 / 밤',
          '워터 / 밀크',
          '필링 / 스크럽',
          '티슈 / 패드',
          '립 / 아이 리무버',
        ],
      },
      {
        key: 'suncare',
        title: '선케어',
        items: ['선크림', '선스틱', '선쿠션', '선스프레이', '선패치', '태닝 / 애프터선'],
      },
      {
        key: 'mens',
        title: '맨즈케어',
        items: ['스킨 / 토너', '올인원 로션', '메이크업', '쉐이빙 / 왁싱'],
      },
      {
        key: 'body',
        title: '바디케어',
        items: [
          '바디로션 / 크림 / 오일 / 미스트',
          '바디워시 / 스크럽',
          '제모 / 왁스',
          '핸드크림 / 핸드워시',
          '풋케어',
          '데오도란트',
        ],
      },
      {
        key: 'hair',
        title: '헤어케어',
        items: [
          '샴푸 / 린스 / 컨디셔너 / 트리트먼트',
          '헤어팩 / 두피 케어 팩',
          '헤어토닉 / 두피토닉',
          '헤어에센스 / 세럼 / 오일',
          '왁스 / 젤 / 무스 / 스프레이 / 픽서',
        ],
      },
      {
        key: 'eyelash',
        title: '속눈썹 / 네일',
        items: [
          '속눈썹 펌제',
          '속눈썹 에센스 / 세럼 / 앰플',
          '속눈썹 영양 케어',
          '네일 케어',
        ],
      },
      {
        key: 'pigment',
        title: '반영구 색소',
        items: ['반영구화장 색소', '반영구 케어', '재생크림'],
      },
    ],
  },
  moq: {
    eyebrow: 'MOQ',
    title: '300개부터 시작할 수 있습니다',
    body: '소량 서비스는 3종 이상 · 종당 100개부터 진행됩니다.\n다른 곳에서 막히던 최소 수량 장벽을 낮췄습니다.',
    rowLabels: {
      minOrder: '최소 수량',
      materials: '부자재',
      sample: '시제품',
      reorder: '2차 발주',
    },
    columns: [
      {
        key: 'oem-small',
        label: 'OEM 소량',
        highlight: true,
        minOrder: '3종 이상\n100개 × 3 = 300개',
        materials: '용기 100개\n라벨 1,000개 · 박스 3,000개',
        sample: '2회\n3회부터 비용 발생',
        reorder: '500개',
      },
      {
        key: 'oem',
        label: 'OEM',
        minOrder: '1,000 / 3,000 / 5,000개',
        materials: '—',
        sample: '—',
        reorder: '—',
      },
      {
        key: 'odm-small',
        label: 'ODM(컨설팅) 소량',
        highlight: true,
        minOrder: '3종 이상\n100개 × 3 = 300개',
        materials: '용기 100개\n라벨 1,000개 · 박스 3,000개',
        sample: '5회\n대면 미팅 2회',
        reorder: '500개',
      },
      {
        key: 'odm',
        label: 'ODM(컨설팅)',
        minOrder: '1,000 / 3,000 / 5,000개',
        materials: '—',
        sample: '—',
        reorder: '—',
      },
    ],
    note: '※ ODM 소량 서비스는 컨설팅 비용 1,000,000원이 별도 발생합니다.',
  },
  pricing: {
    eyebrow: 'Price',
    title: '단가를 먼저 공개합니다',
    body: '개당 금액이며 용량과 성분 함량에 따라 변동됩니다.\n문의 전에 예산을 가늠할 수 있도록 공개합니다.',
    tableHead: ['OEM 소량 · 개당', '100개', '500개', '1,000개'],
    rows: [
      { item: '오오바 쿨링 미스트 100ml', values: ['5,500 원', '4,500 원', '3,500 원'] },
      { item: '미백크림 나이아신아마이드 30ml', values: ['9,500 원', '8,000 원', '6,800 원'] },
      { item: '이데베논 크림 30ml', values: ['10,500 원', '9,000 원', '7,800 원'] },
    ],
    exampleTitle: '3종 300개 발주 시 — 예시',
    exampleHead: ['품목', '수량', '금액'],
    exampleRows: [
      { item: '화장품 3종', qty: '300개', amount: '2,550,000 원' },
      { item: '용기 3종', qty: '300개', amount: '300,000 원' },
      { item: '박스 (디자인 포함)', qty: '3,000개', amount: '980,000 원' },
      { item: '라벨 5종 (디자인 포함)', qty: '5,000개', amount: '600,000 원' },
      { item: '합계 (ODM 컨설팅 포함)', qty: '', amount: '5,430,000 원' },
    ],
    note: '※ 재발주 시 500개 단위 · 박스와 라벨 비용은 발생하지 않습니다.',
  },
  process: {
    eyebrow: 'Process',
    title: '단계별 진행 프로세스',
    body: '상담부터 출고와 사후관리까지,\n브랜드의 상황에 맞는 단계별 프로세스로 진행합니다.',
    steps: [
      { step: '01', title: '상담 및 기획', body: '프로젝트 목적, 희망 품목, 브랜드 방향을 확인합니다.' },
      { step: '02', title: '제형 개발 & 샘플링', body: '제품 제형을 개발하고 샘플을 통해 방향을 조정합니다.' },
      { step: '03', title: '디자인 & 패키지 디자인', body: '용기, 라벨, 패키지 디자인 방향을 구체화합니다.' },
      { step: '04', title: '견적 및 MOQ 확정', body: '품목과 수량에 따른 견적 및 MOQ 조건을 확정합니다.' },
      { step: '05', title: '부자재 입고 / 생산 / 포장', body: '부자재 입고 후 생산, 충진, 포장 과정을 진행합니다.' },
      { step: '06', title: '출고 및 사후관리', body: '완제품 출고 후 필요한 사후관리까지 지원합니다.' },
    ],
  },
  productionGuide: {
    eyebrow: 'Production Guide',
    title: '소량 생산부터 대량 생산까지',
    body: '브랜드 단계에 맞는 생산 조건을 제안합니다.\n품목, 용기, 성분, 수량에 따라 MOQ와 견적이 달라질 수 있으므로\n정확한 조건은 상담을 통해 안내드립니다.',
    cards: [
      { title: 'Small-batch Production', body: '소량 생산부터 시작해 시장 검증과 빠른 출시를 지원합니다.' },
      { title: 'Custom Formula / Package', body: '브랜드 콘셉트에 맞춘 제형과 패키지를 함께 설계합니다.' },
      { title: 'Consultation-based Quotation', body: '품목·수량 조건을 검토해 합리적인 견적을 안내드립니다.' },
    ],
    cta: '내 제품 MOQ 상담받기',
  },
  partners: {
    eyebrow: 'Partners',
    title: 'Business Partners',
    body: '다양한 브랜드, 기관, 교육·뷰티 관련 파트너와 함께해왔습니다.',
    list: [
      '라헬', '인덕대학교', '오뉴월색소', '한국패디협회', '서정대학교', '몰리몰리',
      '퓨스코어', '에비에', 'PBS', '셀킨코스메틱', '차의과대학교', 'GLK바이오',
      '셀코스', '닥터펌', '아리벨', '숙명여자대학교', '에리카', '리나코리아', '오뉴월의새벽',
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Start Your Project',
    body: '제품 아이디어와 브랜드 방향을 남겨주시면,\n생산 가능성과 진행 조건을 검토해 안내드립니다.',
    fields: {
      name: '이름',
      company: '회사명',
      email: '이메일',
      phone: '연락처',
      serviceType: '희망 서비스',
      productCategory: '희망 품목',
      quantity: '예상 수량',
      brandStatus: '브랜드 보유 여부',
      message: '문의 내용',
      agreement: '개인정보 수집 및 이용에 동의합니다.',
    },
    serviceOptions: ['OEM', 'ODM', 'Consulting', 'Other'],
    brandOptions: ['기존 브랜드', '신규 브랜드', '준비 중'],
    submit: '문의 보내기',
    placeholderNotice:
      '메일 작성 창이 열립니다. 창이 열리지 않으면 onewwol1210@naver.com 으로 보내주세요.',
    successNotice: '문의가 정상적으로 접수되었습니다. 확인 후 회신드리겠습니다.',
    errorNotice:
      '전송에 실패했습니다. 잠시 후 다시 시도하시거나 onewwol1210@naver.com 으로 보내주세요.',
    validation: {
      name: '이름을 입력해주세요.',
      email: '올바른 이메일을 입력해주세요.',
      message: '문의 내용을 입력해주세요.',
      agreement: '개인정보 수집 및 이용에 동의해주세요.',
    },
  },
  footer: {
    description: '화장품 | 코스메슈티컬 | 더마코스메틱 | 반영구색소 | OEM/ODM',
    biz: '화장품책임판매업자 · 오뉴월컴퍼니',
    address: '경기도 화성시 동탄구 동탄기흥로 393-20 1동 113호 (파라곤스퀘어)',
    email: 'onewwol1210@naver.com',
    phone: '070-7633-1210',
    nav: ['About', 'Services', 'Capabilities', 'Process', 'Partners', 'Contact'],
    rights: '© onewwol company. All rights reserved.',
  },
};
